language: php

php:
  - 5.5
  - 5.6

branches:
  only:
    - master
    - development
    - /^feature\/.+$/

before_script:
 - git checkout $TRAVIS_BRANCH
 - sh build/tools/update_tools.sh
 - php build/tools/composer.phar install --prefer-dist -o --no-interaction
 - mkdir build/logs

script:
 - php build/tools/phpunit.phar -c build/

after_script:
 - php vendor/bin/coveralls -c ./.coveralls.yml -v --exclude-no-stmt
